const mongoose = require('mongoose');
const fs = require('fs');
const path = require('path');
require('dotenv').config();

const Product = require('../src/models/product.model');

const importData = async () => {
    try {
        await mongoose.connect(process.env.MONGO_URI);
        console.log('✅ Connected to MongoDB');

        // The processed product.json only had 5 products.
        // I will define the full list here to ensure nothing is lost.
        const products = [
            {
                "title": "Samsung Galaxy S24 8GB 256GB",
                "slug": "samsung-galaxy-s24-8-256",
                "description": "Samsung Galaxy S24 powered by Exynos 2400 processor with 6.2-inch Dynamic AMOLED 2X display, 50MP triple camera and 4000mAh battery.",
                "shortDescription": "8GB RAM | 256GB | 50MP | AMOLED",
                "category": "69958d7d2cd735f0f3a65da2",
                "subcategory": "69958d7e2cd735f0f3a65da4",
                "brand": "Samsung",
                "sku": "SAMS-S24-8-256",
                "price": 74999,
                "comparePrice": 79999,
                "costPrice": 56000,
                "stock": 45,
                "lowStockThreshold": 8,
                "tags": ["mobile", "samsung", "5g", "android"],
                "isActive": true,
                "isFeatured": true,
                "rating": { "average": 4.5, "count": 12 },
                "images": [{ "url": "https://images.samsung.com/is/image/samsung/p6pim/in/sm-s921bzkcins/gallery/in-galaxy-s24-s921-488306-sm-s921bzkcins-539573207" }]
            },
            {
                "title": "Apple iPhone 15 128GB",
                "slug": "iphone-15-128gb",
                "description": "Apple iPhone 15 with A16 Bionic chip, 48MP main camera, Super Retina XDR display and USB-C connectivity.",
                "shortDescription": "A16 Bionic | 48MP | 6.1-inch",
                "category": "69958d7d2cd735f0f3a65da2",
                "subcategory": "69958d7e2cd735f0f3a65da4",
                "brand": "Apple",
                "sku": "APL-IP15-128",
                "price": 79900,
                "comparePrice": 84900,
                "costPrice": 61000,
                "stock": 38,
                "lowStockThreshold": 6,
                "tags": ["iphone", "apple", "ios", "5g"],
                "isActive": true,
                "isFeatured": true,
                "rating": { "average": 4.7, "count": 25 },
                "images": [{ "url": "https://store.storeimages.cdn-apple.com/4668/as-images.apple.com/is/iphone-15-black-select-202309" }]
            },
            {
                "title": "OnePlus 12 12GB 256GB",
                "slug": "oneplus-12-12-256",
                "description": "OnePlus 12 featuring Snapdragon 8 Gen 3 processor, 120Hz AMOLED display and Hasselblad 50MP camera system.",
                "shortDescription": "12GB RAM | Snapdragon 8 Gen 3 | 50MP",
                "category": "69958d7d2cd735f0f3a65da2",
                "subcategory": "69958d7e2cd735f0f3a65da4",
                "brand": "OnePlus",
                "sku": "ONEPLUS-12-12-256",
                "price": 64999,
                "comparePrice": 69999,
                "costPrice": 48000,
                "stock": 52,
                "lowStockThreshold": 10,
                "tags": ["oneplus", "5g", "android"],
                "isActive": true,
                "isFeatured": true,
                "rating": { "average": 4.4, "count": 18 },
                "images": [{ "url": "https://image01.oneplus.net/ebp/202401/12/1-m00-3e-26-rb8bwlv0g0uaf9xzaa.jpg" }]
            },
            {
                "title": "Xiaomi 14 8GB 256GB",
                "slug": "xiaomi-14-8-256",
                "description": "Xiaomi 14 powered by Snapdragon 8 Gen 3 with Leica 50MP camera and 120Hz AMOLED display.",
                "shortDescription": "8GB RAM | Leica Camera | 120Hz",
                "category": "69958d7d2cd735f0f3a65da2",
                "subcategory": "69958d7e2cd735f0f3a65da4",
                "brand": "Xiaomi",
                "sku": "MI-14-8-256",
                "price": 59999,
                "comparePrice": 64999,
                "costPrice": 45000,
                "stock": 41,
                "lowStockThreshold": 7,
                "tags": ["xiaomi", "5g", "android"],
                "isActive": true,
                "isFeatured": false,
                "rating": { "average": 4.3, "count": 9 },
                "images": [{ "url": "https://i02.appmifile.com/mi-com-product/fly-birds/xiaomi-14/gallery1.jpg" }]
            },
            {
                "title": "Nothing Phone (2) 12GB 256GB",
                "slug": "nothing-phone-2-12-256",
                "description": "Nothing Phone (2) with Snapdragon 8+ Gen 1 processor, Glyph interface and dual 50MP cameras.",
                "shortDescription": "Glyph Interface | 12GB | 50MP",
                "category": "69958d7d2cd735f0f3a65da2",
                "subcategory": "69958d7e2cd735f0f3a65da4",
                "brand": "Nothing",
                "sku": "NOTHING-P2-12-256",
                "price": 44999,
                "comparePrice": 49999,
                "costPrice": 33500,
                "stock": 33,
                "lowStockThreshold": 6,
                "tags": ["nothing", "5g", "android"],
                "isActive": true,
                "isFeatured": false,
                "rating": { "average": 4.2, "count": 11 },
                "images": [{ "url": "https://cdn.nothing.tech/media/catalog/product/p/h/phone-2-black-front.jpg" }]
            },
            {
                "title": "iQOO 12 12GB 256GB",
                "slug": "iqoo-12-12-256",
                "description": "iQOO 12 powered by Snapdragon 8 Gen 3 processor with 144Hz AMOLED display and 50MP triple camera setup.",
                "shortDescription": "12GB RAM | 144Hz | Snapdragon 8 Gen 3",
                "category": "69958d7d2cd735f0f3a65da2",
                "subcategory": "69958d7e2cd735f0f3a65da4",
                "brand": "iQOO",
                "sku": "IQOO-12-12-256",
                "price": 52999,
                "comparePrice": 57999,
                "costPrice": 39500,
                "stock": 48,
                "lowStockThreshold": 8,
                "tags": ["iqoo", "5g", "android"],
                "isActive": true,
                "isFeatured": true,
                "rating": { "average": 4.4, "count": 16 },
                "images": [{ "url": "https://in-exstatic-vivofs.vivo.com/PSee2l50xoirPK7y/1700123456789/iqoo12-front.png" }]
            },
            {
                "title": "Samsung Galaxy A55 8GB 128GB",
                "slug": "samsung-galaxy-a55-8-128",
                "description": "Samsung Galaxy A55 featuring Exynos 1480 chipset, 120Hz Super AMOLED display and 50MP OIS camera.",
                "shortDescription": "8GB RAM | 50MP OIS | 120Hz AMOLED",
                "category": "69958d7d2cd735f0f3a65da2",
                "subcategory": "69958d7e2cd735f0f3a65da4",
                "brand": "Samsung",
                "sku": "SAMS-A55-8-128",
                "price": 39999,
                "comparePrice": 42999,
                "costPrice": 30000,
                "stock": 55,
                "lowStockThreshold": 10,
                "tags": ["samsung", "5g", "android"],
                "isActive": true,
                "isFeatured": false,
                "rating": { "average": 4.3, "count": 22 },
                "images": [{ "url": "https://images.samsung.com/is/image/samsung/p6pim/in/sm-a556bzkcins/gallery/in-galaxy-a55-488001" }]
            },
            {
                "title": "Realme GT 6 12GB 256GB",
                "slug": "realme-gt-6-12-256",
                "description": "Realme GT 6 powered by Snapdragon 8s Gen 3 with 120Hz AMOLED display and 5500mAh battery.",
                "shortDescription": "12GB RAM | 5500mAh | Snapdragon 8s Gen 3",
                "category": "69958d7d2cd735f0f3a65da2",
                "subcategory": "69958d7e2cd735f0f3a65da4",
                "brand": "Realme",
                "sku": "REALME-GT6-12-256",
                "price": 42999,
                "comparePrice": 45999,
                "costPrice": 32000,
                "stock": 36,
                "lowStockThreshold": 6,
                "tags": ["realme", "5g", "android"],
                "isActive": true,
                "isFeatured": false,
                "rating": { "average": 4.2, "count": 14 },
                "images": [{ "url": "https://image01.realme.net/general/202406/realme-gt6-front.png" }]
            },
            {
                "title": "Google Pixel 8 8GB 128GB",
                "slug": "google-pixel-8-8-128",
                "description": "Google Pixel 8 with Tensor G3 processor, 50MP AI camera and 120Hz OLED display.",
                "shortDescription": "Tensor G3 | 50MP | 120Hz OLED",
                "category": "69958d7d2cd735f0f3a65da2",
                "subcategory": "69958d7e2cd735f0f3a65da4",
                "brand": "Google",
                "sku": "PIXEL8-8-128",
                "price": 75999,
                "comparePrice": 79999,
                "costPrice": 59000,
                "stock": 29,
                "lowStockThreshold": 5,
                "tags": ["google", "pixel", "5g"],
                "isActive": true,
                "isFeatured": true,
                "rating": { "average": 4.6, "count": 19 },
                "images": [{ "url": "https://lh3.googleusercontent.com/pixel8-front.png" }]
            },
            {
                "title": "Vivo V30 Pro 12GB 256GB",
                "slug": "vivo-v30-pro-12-256",
                "description": "Vivo V30 Pro with Dimensity 8200 chipset, 50MP triple camera and curved AMOLED display.",
                "shortDescription": "12GB RAM | 50MP Triple Camera",
                "category": "69958d7d2cd735f0f3a65da2",
                "subcategory": "69958d7e2cd735f0f3a65da4",
                "brand": "Vivo",
                "sku": "VIVO-V30PRO-12-256",
                "price": 41999,
                "comparePrice": 44999,
                "costPrice": 31000,
                "stock": 34,
                "lowStockThreshold": 6,
                "tags": ["vivo", "5g", "android"],
                "isActive": true,
                "isFeatured": false,
                "rating": { "average": 4.3, "count": 13 },
                "images": [{ "url": "https://in-exstatic-vivofs.vivo.com/PSee2l50xoirPK7y/v30pro-front.png" }]
            },
            {
                "title": "Motorola Edge 50 Pro 12GB 256GB",
                "slug": "motorola-edge-50-pro-12-256",
                "description": "Motorola Edge 50 Pro with Snapdragon 7 Gen 3 processor, 144Hz pOLED display, 50MP OIS camera and 125W TurboPower charging.",
                "shortDescription": "12GB RAM | 144Hz pOLED | 125W Charging",
                "category": "69958d7d2cd735f0f3a65da2",
                "subcategory": "69958d7e2cd735f0f3a65da4",
                "brand": "Motorola",
                "sku": "MOTO-EDGE50PRO-12-256",
                "price": 36999,
                "comparePrice": 39999,
                "costPrice": 27500,
                "stock": 40,
                "lowStockThreshold": 7,
                "tags": ["motorola", "5g", "android"],
                "isActive": true,
                "isFeatured": false,
                "rating": { "average": 4.2, "count": 17 },
                "images": [{ "url": "https://motorola-cdn.com/edge50pro-front.jpg" }]
            },
            {
                "title": "Redmi Note 13 Pro+ 12GB 256GB",
                "slug": "redmi-note-13-pro-plus-12-256",
                "description": "Redmi Note 13 Pro+ featuring 200MP camera, Dimensity 7200 Ultra processor and 120W HyperCharge.",
                "shortDescription": "200MP Camera | 120W Charging | 12GB RAM",
                "category": "69958d7d2cd735f0f3a65da2",
                "subcategory": "69958d7e2cd735f0f3a65da4",
                "brand": "Xiaomi",
                "sku": "REDMI-N13PPLUS-12-256",
                "price": 31999,
                "comparePrice": 34999,
                "costPrice": 24000,
                "stock": 58,
                "lowStockThreshold": 10,
                "tags": ["redmi", "5g", "android"],
                "isActive": true,
                "isFeatured": false,
                "rating": { "average": 4.3, "count": 28 },
                "images": [{ "url": "https://i02.appmifile.com/redmi-note13proplus-front.jpg" }]
            },
            {
                "title": "ASUS ROG Phone 8 16GB 512GB",
                "slug": "asus-rog-phone-8-16-512",
                "description": "ASUS ROG Phone 8 gaming smartphone with Snapdragon 8 Gen 3, 165Hz AMOLED display and advanced cooling system.",
                "shortDescription": "16GB RAM | 165Hz | Gaming Beast",
                "category": "69958d7d2cd735f0f3a65da2",
                "subcategory": "69958d7e2cd735f0f3a65da4",
                "brand": "ASUS",
                "sku": "ASUS-ROG8-16-512",
                "price": 94999,
                "comparePrice": 99999,
                "costPrice": 72000,
                "stock": 22,
                "lowStockThreshold": 5,
                "tags": ["asus", "gaming", "5g", "android"],
                "isActive": true,
                "isFeatured": true,
                "rating": { "average": 4.6, "count": 9 },
                "images": [{ "url": "https://dlcdnwebimgs.asus.com/rog-phone8-front.png" }]
            },
            {
                "title": "POCO X6 Pro 12GB 256GB",
                "slug": "poco-x6-pro-12-256",
                "description": "POCO X6 Pro with Dimensity 8300 Ultra processor, 120Hz AMOLED display and 5000mAh battery.",
                "shortDescription": "Dimensity 8300 | 12GB RAM | 120Hz",
                "category": "69958d7d2cd735f0f3a65da2",
                "subcategory": "69958d7e2cd735f0f3a65da4",
                "brand": "POCO",
                "sku": "POCO-X6PRO-12-256",
                "price": 28999,
                "comparePrice": 31999,
                "costPrice": 21000,
                "stock": 64,
                "lowStockThreshold": 12,
                "tags": ["poco", "5g", "android"],
                "isActive": true,
                "isFeatured": false,
                "rating": { "average": 4.1, "count": 32 },
                "images": [{ "url": "https://i02.appmifile.com/poco-x6pro-front.jpg" }]
            },
            {
                "title": "Apple iPhone 15 Pro 256GB",
                "slug": "iphone-15-pro-256gb",
                "description": "Apple iPhone 15 Pro with A17 Pro chip, titanium design, 48MP Pro camera system and ProMotion display.",
                "shortDescription": "A17 Pro | Titanium | 48MP Pro Camera",
                "category": "69958d7d2cd735f0f3a65da2",
                "subcategory": "69958d7e2cd735f0f3a65da4",
                "brand": "Apple",
                "sku": "APL-IP15PRO-256",
                "price": 134900,
                "comparePrice": 139900,
                "costPrice": 105000,
                "stock": 18,
                "lowStockThreshold": 4,
                "tags": ["apple", "iphone", "5g", "ios"],
                "isActive": true,
                "isFeatured": true,
                "rating": { "average": 4.8, "count": 21 },
                "images": [{ "url": "https://store.storeimages.cdn-apple.com/4668/as-images.apple.com/is/iphone-15-pro-black-titanium-select" }]
            },
            {
                "title": "Samsung Galaxy Z Flip5 8GB 256GB",
                "slug": "samsung-galaxy-z-flip5-8-256",
                "description": "Samsung Galaxy Z Flip5 foldable smartphone with Snapdragon 8 Gen 2 processor, Flex Window display and 12MP dual camera system.",
                "shortDescription": "Foldable | Snapdragon 8 Gen 2 | 256GB",
                "category": "69958d7d2cd735f0f3a65da2",
                "subcategory": "69958d7e2cd735f0f3a65da4",
                "brand": "Samsung",
                "sku": "SAMS-ZFLIP5-256",
                "price": 99999,
                "comparePrice": 104999,
                "costPrice": 76000,
                "stock": 21,
                "lowStockThreshold": 5,
                "tags": ["samsung", "foldable", "5g"],
                "isActive": true,
                "isFeatured": true,
                "rating": { "average": 4.4, "count": 14 },
                "images": [{ "url": "https://images.samsung.com/is/image/samsung/p6pim/in/sm-f731bzkdins/gallery/in-galaxy-z-flip5" }]
            },
            {
                "title": "OnePlus Nord CE4 8GB 128GB",
                "slug": "oneplus-nord-ce4-8-128",
                "description": "OnePlus Nord CE4 powered by Snapdragon 7 Gen 3 processor with 120Hz AMOLED display and 5500mAh battery.",
                "shortDescription": "8GB RAM | 120Hz AMOLED | 5500mAh",
                "category": "69958d7d2cd735f0f3a65da2",
                "subcategory": "69958d7e2cd735f0f3a65da4",
                "brand": "OnePlus",
                "sku": "ONEPLUS-NORDCE4-8-128",
                "price": 24999,
                "comparePrice": 27999,
                "costPrice": 18500,
                "stock": 72,
                "lowStockThreshold": 15,
                "tags": ["oneplus", "5g", "android"],
                "isActive": true,
                "isFeatured": false,
                "rating": { "average": 4.2, "count": 37 },
                "images": [{ "url": "https://image01.oneplus.net/nordce4-front.png" }]
            },
            {
                "title": "Vivo X100 12GB 256GB",
                "slug": "vivo-x100-12-256",
                "description": "Vivo X100 featuring Dimensity 9300 processor, ZEISS 50MP triple camera and curved AMOLED display.",
                "shortDescription": "ZEISS Camera | 12GB RAM | 120Hz",
                "category": "69958d7d2cd735f0f3a65da2",
                "subcategory": "69958d7e2cd735f0f3a65da4",
                "brand": "Vivo",
                "sku": "VIVO-X100-12-256",
                "price": 63999,
                "comparePrice": 67999,
                "costPrice": 48000,
                "stock": 30,
                "lowStockThreshold": 6,
                "tags": ["vivo", "5g", "android"],
                "isActive": true,
                "isFeatured": true,
                "rating": { "average": 4.5, "count": 11 },
                "images": [{ "url": "https://in-exstatic-vivofs.vivo.com/x100-front.png" }]
            },
            {
                "title": "Google Pixel 8 Pro 12GB 128GB",
                "slug": "google-pixel-8-pro-12-128",
                "description": "Google Pixel 8 Pro with Tensor G3 chipset, 50MP Pro camera system and 6.7-inch LTPO OLED display.",
                "shortDescription": "Tensor G3 | Pro Camera | 120Hz LTPO",
                "category": "69958d7d2cd735f0f3a65da2",
                "subcategory": "69958d7e2cd735f0f3a65da4",
                "brand": "Google",
                "sku": "PIXEL8PRO-12-128",
                "price": 106999,
                "comparePrice": 112999,
                "costPrice": 82000,
                "stock": 17,
                "lowStockThreshold": 4,
                "tags": ["google", "pixel", "5g"],
                "isActive": true,
                "isFeatured": true,
                "rating": { "average": 4.7, "count": 15 },
                "images": [{ "url": "https://lh3.googleusercontent.com/pixel8pro-front.png" }]
            },
            {
                "title": "Nothing Phone (2a) 8GB 128GB",
                "slug": "nothing-phone-2a-8-128",
                "description": "Nothing Phone (2a) powered by Dimensity 7200 Pro processor with Glyph Interface and dual 50MP camera setup.",
                "shortDescription": "Glyph Interface | 8GB RAM | 50MP",
                "category": "69958d7d2cd735f0f3a65da2",
                "subcategory": "69958d7e2cd735f0f3a65da4",
                "brand": "Nothing",
                "sku": "NOTHING-P2A-8-128",
                "price": 23999,
                "comparePrice": 25999,
                "costPrice": 17500,
                "stock": 68,
                "lowStockThreshold": 12,
                "tags": ["nothing", "5g", "android"],
                "isActive": true,
                "isFeatured": false,
                "rating": { "average": 4.3, "count": 24 },
                "images": [{ "url": "https://cdn.nothing.tech/media/catalog/product/p/h/phone2a-front.jpg" }]
            }
        ];

        console.log(`Prepared ${products.length} products for import.`);

        // Insert or update
        for (const p of products) {
            await Product.findOneAndUpdate(
                { slug: p.slug },
                p,
                { upsert: true, new: true }
            );
        }

        console.log('✅ Products imported/updated successfully!');
        process.exit(0);
    } catch (err) {
        console.error('❌ Import failed:', err);
        process.exit(1);
    }
};

importData();
